[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
helloworld = "9EG9CqNvAqNHkrNvNSeCSoDyGGBeSp7mXPd6CyEY4zof"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = 'C:\Users\admin\.config/solana/id.json'

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
